name: 8.0.$(rev:r)

variables:
  - group: shared_buddy_variable_group

trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    include:
      - /src/Adliance.Storyblok/

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self

- task: UseDotNet@2
  displayName: "Install .NET"
  inputs:
    version: '8.0.x'
    packageType: sdk

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    projects: 'src/Adliance.Storyblok/Adliance.Storyblok.csproj'
    arguments: '--configuration Release'

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: test
    projects: 'test/Adliance.Storyblok.Tests/Adliance.Storyblok.Tests.csproj'
    arguments: '--configuration Release'

- task: DotNetCoreCLI@2
  displayName: Pack
  inputs:
    command: pack
    packagesToPack: 'src/Adliance.Storyblok/Adliance.Storyblok.csproj'
    configuration: 'Release'
    versioningScheme: byBuildNumber
    outputDir: '$(Build.ArtifactStagingDirectory)'

- task: DotNetCoreCLI@2
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  displayName: Push
  inputs:
    command: 'custom'
    custom: 'nuget'
    arguments: >
      push "$(Build.ArtifactStagingDirectory)/*.nupkg"
      --source "https://api.nuget.org/v3/index.json"
      --api-key "$(nuget_api_key)"
